sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t summertanks/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true summertanks/docker-react npm run test