sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t summertanks/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true summertanks/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name:  "elasticbeanstalk-us-east-1-708384565250"
  bucket_path:  "docker-react"
  on:
    branch: master

  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
